### ISSUE TITLE
Accuracy Decreasing with stages

### ISSUE THREAD

**Issue by tarun005** [XJTU-XGU/RSDA#1]
Thanks for the code!

I am running the code on the visDA dataset, and I am observing that the precision is continuously decreasing throughout the training. It is highest in stage 0, and then decreasing from there. Did you observe any similar trends during training?

**Comment by XJTU-XGU** [comment]
Thanks a lot for your interest in our paper. The released code is for the Office-31 dataset. The codes for the visDA and the Office-Home datasets are slightly different from the released one, because some hyper-paramters need to be changed, e.g., the radius and the iteration steps.  For this reason, we will release the codes for visDA and Office-Home individually. The  issues in the released code have been fixed, and we will re-upload it as soon as possible.
