### ISSUE TITLE
Information leakage

### ISSUE THREAD

**Issue by shuaiyu5** [XJTU-XGU/RSDA#4]
Excellent work! However, I have observed that the data list would be rewritten after each iteration based on best acc in val_loader, the new pseudo-labeling data list will be utilized in the next training phase. Are the whole best results selection processes involved in Information Leakage?

**Comment by XJTU-XGU** [comment]
Thanks for your interest. This is the topic of model selection. Since there is no labeled validation dataset on the target domain, we use the best model in the released code, for simplicity. However, there are some more reasonable but more complicated approaches to select the model that does not suffer from overfitting, such as early stopping. We also find the early stopping achieved similar results.

**Comment by XJTU-XGU** [comment]
Thanks for your interest. This is the topic of model selection. Since there is no labeled validation dataset on the target domain, for simplicity, we select the best model in this code. There are some more reasonable but more complicated strategies to select a model that does not suffer from overfitting, such as Deep Embedded Validation. We find that the  Deep Embedded Validation achieves similar results.

**Comment by shuaiyu5** [comment]
Thanks for your reply. Actually, I would not treat this phenomenon as over-fitting. the validation acc has increased greatly and then slowly decreased to a convergence value which is the pseudo-labeling dataset acc. In UDA setting, without labeled data, the key is the model selection, traditional methods such as Early stopping can't work well in various transfer tasks(choosing stop iterations also needs labels!).

**Comment by XJTU-XGU** [comment]
Thanks. I think model selection for UDA is a fundamental but still unsolved problem though there are few works.
